string = "Thread"
other_string = "sewing kit"
integer = 5
float = 4.76
boolean = false
have_sleep = false
array = [15,"fifteen",true]
other_array = [63,6.098,"blah"]
hash = {name: Rin, language: Ruby}
